version: '3.8'

services:
  mcp-ai-testing:
    build: .
    container_name: mcp-ai-testing
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HEADLESS=true
      - DEFAULT_BROWSER=chromium
    volumes:
      - ./reports:/app/reports
      - ./test-data:/app/test-data
    command: >
      python cli.py test 
      --url https://demo.playwright.dev/todomvc/ 
      --browser chromium 
      --headless 
      --max-tests 5
    depends_on:
      - redis
      - postgres
    networks:
      - testing-network

  # Optional: Redis for caching test results
  redis:
    image: redis:7-alpine
    container_name: mcp-redis
    ports:
      - "6379:6379"
    networks:
      - testing-network

  # Optional: PostgreSQL for test history
  postgres:
    image: postgres:15-alpine
    container_name: mcp-postgres
    environment:
      - POSTGRES_DB=mcp_testing
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - testing-network

  # Optional: Web dashboard for test results
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: mcp-dashboard
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://mcp_user:mcp_password@postgres:5432/mcp_testing
    depends_on:
      - postgres
    networks:
      - testing-network

volumes:
  postgres_data:

networks:
  testing-network:
    driver: bridge