name: AI-Powered Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  #schedule:
    # Run tests daily at 2 AM UTC
    # - cron: '0 2 * * *'

jobs:
  ai-testing:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        
    - name: Run AI-powered tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        BROWSER: ${{ matrix.browser }}
        HEADLESS: true
      run: |
        python -m pytest tests/ -v --browser=${{ matrix.browser }}
        
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports-${{ matrix.browser }}
        path: |
          reports/
          screenshots/
          
    - name: Upload failure screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failure-screenshots-${{ matrix.browser }}
        path: failure_*.png
